import type {
  AtomDefinition,
  EdgeDefinition,
  LayerDefinition,
  PlatformConfig,
  PlatformDefinition,
  PlatformId,
  TraceEvent,
} from "@/types/trace";
import { isUserQuestionEvent } from "../lib/trace-event-kind.ts";

export const topologyGeometry = {
  nodeWidth: 180,
  nodeHeight: 84,
};

const layers: LayerDefinition[] = [
  {
    id: "session-control",
    index: "01",
    label: "Session Control",
    description: "Run lifecycle and checkpoints",
    tone: "prompt",
    position: { x: 30, y: 40 },
    width: 230,
    height: 620,
  },
  {
    id: "agent-execute",
    index: "02",
    label: "Agent Execute",
    description: "Turn-scoped reasoning and routing",
    tone: "reasoning",
    position: { x: 300, y: 40 },
    width: 1110,
    height: 620,
  },
  {
    id: "memory-system",
    index: "03",
    label: "Memory System",
    description: "Recall and working capture",
    tone: "agent",
    position: { x: 30, y: 700 },
    width: 520,
    height: 170,
  },
  {
    id: "capability-runtime",
    index: "04",
    label: "Capability Runtime",
    description: "Tool resolution, execution, and results",
    tone: "tool",
    position: { x: 590, y: 700 },
    width: 820,
    height: 170,
  },
  {
    id: "quality-gates",
    index: "05",
    label: "Quality Gates",
    description: "Validate and commit output",
    tone: "complete",
    position: { x: 30, y: 910 },
    width: 780,
    height: 170,
  },
  {
    id: "telemetry",
    index: "06",
    label: "Telemetry",
    description: "Trace and trajectory records",
    tone: "signal",
    position: { x: 850, y: 910 },
    width: 560,
    height: 170,
  },
];

const atoms: AtomDefinition[] = [
  {
    id: "prompt-input",
    key: "prompt.input",
    label: "Prompt Input",
    section: "Input",
    layer: "session-control",
    kind: "input",
    tone: "prompt",
    position: { x: 55, y: 100 },
    eventTypes: ["UserPromptSubmit"],
    input: ["user.prompt"],
    output: ["normalized.prompt"],
    description: "Captures and normalizes the incoming user request.",
  },
  {
    id: "session-resume",
    key: "session.resume",
    label: "Session Resume",
    section: "Session",
    layer: "session-control",
    kind: "context",
    tone: "session",
    position: { x: 55, y: 210 },
    eventTypes: ["SessionStart"],
    input: ["session.id"],
    output: ["session.state"],
    description: "Restores the active runtime session and persisted context.",
  },
  {
    id: "stage-start",
    key: "stage.start",
    label: "Stage Start",
    section: "Lifecycle",
    layer: "session-control",
    kind: "run",
    tone: "session",
    position: { x: 55, y: 320 },
    eventTypes: ["SessionStart", "UserPromptSubmit"],
    input: ["session.state", "normalized.prompt"],
    output: ["run.context"],
    description: "Opens the execution stage for the current turn.",
  },
  {
    id: "checkpoint",
    key: "stage.checkpoint",
    label: "Checkpoint",
    section: "Lifecycle",
    layer: "session-control",
    kind: "checkpoint",
    tone: "prompt",
    position: { x: 55, y: 430 },
    eventTypes: ["Notification", "PostToolUse"],
    input: ["atom.state"],
    output: ["checkpoint.state"],
    description: "Persists an observable checkpoint during execution.",
  },
  {
    id: "stage-finish",
    key: "stage.finish",
    label: "Stage Finish",
    section: "Lifecycle",
    layer: "session-control",
    kind: "output",
    tone: "complete",
    position: { x: 55, y: 540 },
    eventTypes: ["Stop", "SessionEnd"],
    input: ["run.result"],
    output: ["session.result"],
    description: "Commits the stage result and closes the active turn.",
  },
  {
    id: "run",
    key: "run",
    label: "Run",
    section: "Execution",
    layer: "agent-execute",
    kind: "run",
    tone: "prompt",
    position: { x: 340, y: 100 },
    eventTypes: ["UserPromptSubmit"],
    input: ["run.context"],
    output: ["turn.state"],
    description: "Starts the agent execution loop for the request.",
  },
  {
    id: "agent-select",
    key: "agent.select",
    label: "Agent Select",
    section: "Router",
    layer: "agent-execute",
    kind: "agent",
    tone: "reasoning",
    position: { x: 640, y: 100 },
    eventTypes: ["SessionStart", "SubagentStart"],
    input: ["turn.state", "agent.registry"],
    output: ["selected.agent"],
    description: "Resolves the agent responsible for the current turn.",
  },
  {
    id: "model-invoke",
    key: "model.invoke",
    label: "Model Invoke",
    section: "Model",
    layer: "agent-execute",
    kind: "model",
    tone: "reasoning",
    position: { x: 940, y: 100 },
    eventTypes: [
      "Reasoning",
      "AgentMessage",
      "PreToolUse",
      "Stop",
      "StopFailure",
    ],
    input: ["selected.agent", "model.context"],
    output: ["model.decision"],
    description: "Invokes the model for the active reasoning turn.",
  },
  {
    id: "loop-turn",
    key: "loop.turn",
    label: "Loop Turn",
    section: "Loop",
    layer: "agent-execute",
    kind: "loop",
    tone: "reasoning",
    position: { x: 340, y: 250 },
    eventTypes: ["PreToolUse", "AgentMessage"],
    countEventTypes: ["PreToolUse"],
    input: ["observation", "turn.index"],
    output: ["next.context"],
    description: "Advances execution to the next observable turn.",
  },
  {
    id: "action-gate",
    key: "action.gate",
    label: "Action Gate",
    section: "Decision",
    layer: "agent-execute",
    kind: "gate",
    tone: "reasoning",
    position: { x: 940, y: 250 },
    eventTypes: [
      "PreToolUse",
      "PermissionRequest",
      "Elicitation",
      "Stop",
      "StopFailure",
    ],
    input: ["model.decision", "policy"],
    output: ["tool.route", "reply.route"],
    description: "Routes the model decision to a tool, question, or reply.",
  },
  {
    id: "observation",
    key: "observation",
    label: "Observation",
    section: "Loop",
    layer: "agent-execute",
    kind: "observation",
    tone: "agent",
    position: { x: 340, y: 400 },
    eventTypes: ["PostToolUse", "PostToolUseFailure", "SubagentStop"],
    input: ["tool.result", "agent.result"],
    output: ["loop.observation"],
    description: "Normalizes execution results for the next model turn.",
  },
  {
    id: "tool-call",
    key: "tool.call",
    label: "Tool Call",
    section: "Action",
    layer: "agent-execute",
    kind: "tool",
    tone: "tool",
    position: { x: 640, y: 400 },
    eventTypes: ["PreToolUse", "PostToolUse", "PostToolUseFailure"],
    countEventTypes: ["PreToolUse"],
    input: ["tool.route", "tool.arguments"],
    output: ["tool.request"],
    description: "Dispatches the selected capability and its arguments.",
  },
  {
    id: "usage",
    key: "usage.record",
    label: "Usage",
    section: "Metrics",
    layer: "agent-execute",
    kind: "usage",
    tone: "signal",
    position: { x: 1190, y: 400 },
    eventTypes: ["AgentMessage", "Stop"],
    input: ["model.usage", "runtime.timing"],
    output: ["usage.record"],
    description: "Captures token, latency, and execution usage.",
  },
  {
    id: "handoff",
    key: "handoff",
    label: "Handoff",
    section: "Routing",
    layer: "agent-execute",
    kind: "handoff",
    tone: "signal",
    position: { x: 340, y: 540 },
    eventTypes: ["SubagentStart", "SubagentStop"],
    countEventTypes: ["SubagentStart"],
    input: ["delegated.task"],
    output: ["subagent.request"],
    description: "Delegates work to a child agent and awaits its result.",
  },
  {
    id: "user-question",
    key: "user.question",
    label: "User Question",
    section: "Interaction",
    layer: "agent-execute",
    kind: "question",
    tone: "prompt",
    position: { x: 640, y: 540 },
    eventTypes: [
      "PermissionRequest",
      "PermissionDenied",
      "Elicitation",
      "ElicitationResult",
    ],
    input: ["missing.input", "permission.request"],
    output: ["user.answer"],
    description: "Pauses execution for required user input or approval.",
  },
  {
    id: "final-reply",
    key: "reply.final",
    label: "Final Reply",
    section: "Output",
    layer: "agent-execute",
    kind: "output",
    tone: "complete",
    position: { x: 940, y: 540 },
    eventTypes: ["AgentMessage", "Stop"],
    input: ["reply.route", "model.output"],
    output: ["candidate.response"],
    description: "Composes the user-facing response for the completed run.",
  },
  {
    id: "memory-recall",
    key: "memory.recall",
    label: "Memory Recall",
    section: "Memory",
    layer: "memory-system",
    kind: "context",
    tone: "agent",
    position: { x: 70, y: 750 },
    eventTypes: ["SessionStart", "Notification"],
    input: ["semantic.query"],
    output: ["ranked.memories"],
    description: "Retrieves relevant context for model execution.",
  },
  {
    id: "memory-capture",
    key: "memory.capture",
    label: "Working Capture",
    section: "Memory",
    layer: "memory-system",
    kind: "context",
    tone: "agent",
    position: { x: 330, y: 750 },
    eventTypes: ["AgentMessage", "Notification", "Stop"],
    input: ["loop.observation", "agent.output"],
    output: ["working.memory"],
    description: "Captures durable context produced by the run.",
  },
  {
    id: "tool-resolve",
    key: "tool.resolve",
    label: "Tool Resolve",
    section: "Capability",
    layer: "capability-runtime",
    kind: "tool",
    tone: "tool",
    position: { x: 610, y: 750 },
    eventTypes: ["PreToolUse"],
    input: ["tool.request", "tool.registry"],
    output: ["resolved.tool"],
    description: "Resolves the requested capability implementation.",
  },
  {
    id: "tool-execute",
    key: "tool.execute",
    label: "Tool Execute",
    section: "Capability",
    layer: "capability-runtime",
    kind: "tool",
    tone: "tool",
    position: { x: 810, y: 750 },
    eventTypes: ["PreToolUse", "PostToolUse", "PostToolUseFailure"],
    countEventTypes: ["PreToolUse"],
    input: ["resolved.tool"],
    output: ["tool.output", "tool.error"],
    description: "Executes the capability and captures its output.",
  },
  {
    id: "tool-result",
    key: "tool.result",
    label: "Tool Result",
    section: "Capability",
    layer: "capability-runtime",
    kind: "observation",
    tone: "tool",
    position: { x: 1010, y: 750 },
    eventTypes: ["PostToolUse", "PostToolUseFailure"],
    input: ["tool.output", "tool.error"],
    output: ["tool.result"],
    description: "Publishes the tool output for observation and feedback.",
  },
  {
    id: "agent-result",
    key: "agent.result",
    label: "Agent Result",
    section: "Capability",
    layer: "capability-runtime",
    kind: "subagent",
    tone: "signal",
    position: { x: 1210, y: 750 },
    eventTypes: ["SubagentStop"],
    input: ["subagent.result"],
    output: ["normalized.result"],
    description: "Normalizes capability and child-agent results.",
  },
  {
    id: "quality-gate",
    key: "gate.quality",
    label: "Quality Gate",
    section: "Quality",
    layer: "quality-gates",
    kind: "gate",
    tone: "complete",
    position: { x: 70, y: 960 },
    eventTypes: ["Stop", "SessionEnd"],
    input: ["candidate.response", "acceptance.criteria"],
    output: ["accepted.response", "retry.route"],
    description: "Validates the response against completion criteria.",
  },
  {
    id: "final-artifact",
    key: "artifact.final",
    label: "Final Artifact",
    section: "Quality",
    layer: "quality-gates",
    kind: "output",
    tone: "complete",
    position: { x: 320, y: 960 },
    eventTypes: ["AgentMessage", "Stop"],
    input: ["accepted.response"],
    output: ["rendered.artifact"],
    description: "Materializes the accepted response or code artifact.",
  },
  {
    id: "output-commit",
    key: "output.commit",
    label: "Output Commit",
    section: "Quality",
    layer: "quality-gates",
    kind: "output",
    tone: "complete",
    position: { x: 570, y: 960 },
    eventTypes: ["Stop", "SessionEnd"],
    input: ["rendered.artifact"],
    output: ["run.result"],
    description: "Commits the final result to the session.",
  },
  {
    id: "trace-append",
    key: "telemetry.append",
    label: "Trace Append",
    section: "Telemetry",
    layer: "telemetry",
    kind: "telemetry",
    tone: "signal",
    position: { x: 890, y: 960 },
    eventTypes: [
      "SessionStart",
      "UserPromptSubmit",
      "AgentMessage",
      "Reasoning",
      "PreToolUse",
      "PostToolUse",
      "PostToolUseFailure",
      "PermissionRequest",
      "PermissionDenied",
      "Notification",
      "SubagentStart",
      "SubagentStop",
      "Stop",
      "StopFailure",
      "Elicitation",
      "ElicitationResult",
      "SessionEnd",
    ],
    input: ["atom.event", "timing", "correlation"],
    output: ["trace.record"],
    description: "Appends every atomic transition to the local event stream.",
  },
  {
    id: "trajectory-project",
    key: "trajectory.project",
    label: "Trajectory Project",
    section: "Telemetry",
    layer: "telemetry",
    kind: "telemetry",
    tone: "signal",
    position: { x: 1160, y: 960 },
    eventTypes: ["Stop", "SessionEnd"],
    input: ["trace.record"],
    output: ["trajectory.view"],
    description: "Projects atomic events into the replayable execution path.",
  },
];

const edges: EdgeDefinition[] = [
  ["prompt-input", "session-resume", "", "forward", "source-bottom", "target-top"],
  ["session-resume", "stage-start", "", "forward", "source-bottom", "target-top"],
  ["stage-start", "checkpoint", "", "record", "source-bottom", "target-top"],
  ["checkpoint", "stage-finish", "", "record", "source-bottom", "target-top"],
  ["stage-start", "run", "start", "forward", "source-right", "target-left", [{ x: 280, y: 362 }, { x: 280, y: 142 }]],
  ["run", "loop-turn", "", "reasoning", "source-bottom", "target-top"],
  ["loop-turn", "agent-select", "next turn", "reasoning", "source-right", "target-left", [{ x: 580, y: 292 }, { x: 580, y: 142 }]],
  ["agent-select", "model-invoke", "", "reasoning", "source-right", "target-left"],
  ["model-invoke", "action-gate", "", "reasoning", "source-bottom", "target-top"],
  ["action-gate", "tool-call", "tool", "reasoning", "source-left", "target-top", [{ x: 870, y: 292 }, { x: 870, y: 370 }, { x: 730, y: 370 }], "tool"],
  ["observation", "loop-turn", "", "reasoning", "source-top", "target-bottom", [], "tool"],
  ["observation", "handoff", "", "subagent", "source-bottom", "target-top", [], "subagent"],
  ["tool-call", "user-question", "", "prompt", "source-bottom", "target-top", [], "question"],
  ["action-gate", "final-reply", "final", "forward", "source-bottom", "target-top", [], "complete"],
  ["model-invoke", "usage", "usage", "record", "source-right", "target-top", [{ x: 1160, y: 142 }, { x: 1160, y: 370 }, { x: 1280, y: 370 }]],
  ["final-reply", "stage-finish", "commit", "forward", "source-bottom", "target-right", [{ x: 1030, y: 680 }, { x: 280, y: 680 }, { x: 280, y: 582 }], "complete"],
  ["observation", "memory-capture", "capture", "memory", "source-bottom", "target-top", [{ x: 430, y: 680 }], "tool"],
  ["memory-capture", "memory-recall", "persist", "memory", "source-left", "target-right"],
  ["tool-call", "tool-resolve", "resolve", "tool", "source-bottom", "target-top", [{ x: 730, y: 680 }, { x: 720, y: 680 }], "tool"],
  ["tool-resolve", "tool-execute", "", "tool", "source-right", "target-left", [], "tool"],
  ["tool-execute", "tool-result", "result", "tool", "source-right", "target-left", [], "tool"],
  ["tool-result", "observation", "", "tool", "source-top", "target-right", [], "tool"],
  ["agent-result", "final-reply", "result", "subagent", "source-top", "target-right", [], "tool"],
  ["final-reply", "quality-gate", "evaluate", "forward", "source-bottom", "target-top", [{ x: 1030, y: 890 }, { x: 160, y: 890 }], "complete"],
  ["quality-gate", "final-artifact", "", "forward", "source-right", "target-left", [], "complete"],
  ["final-artifact", "output-commit", "pass", "forward", "source-right", "target-left", [], "complete"],
  ["output-commit", "trace-append", "record", "record", "source-right", "target-left", [], "complete"],
  ["trace-append", "trajectory-project", "", "record", "source-right", "target-left"],
];

const defaultEventAtomMap: Record<string, string> = {
  SessionStart: "session-resume",
  UserPromptSubmit: "run",
  Reasoning: "model-invoke",
  PreToolUse: "tool-call",
  PostToolUse: "tool-result",
  PostToolUseFailure: "tool-result",
  PermissionRequest: "user-question",
  PermissionDenied: "user-question",
  Elicitation: "user-question",
  ElicitationResult: "user-question",
  PreCompact: "trace-append",
  PostCompact: "trace-append",
  Notification: "trace-append",
  SubagentStart: "handoff",
  SubagentStop: "agent-result",
  AgentMessage: "final-reply",
  Stop: "output-commit",
  StopFailure: "model-invoke",
  SessionEnd: "stage-finish",
};

const platformDefinitions: Record<PlatformId, PlatformDefinition> = {
  codex: {
    id: "codex",
    label: "Codex",
    source: "codex",
    runtime: "OpenAI coding runtime",
    eventAtomMap: defaultEventAtomMap,
  },
  claude: {
    id: "claude",
    label: "Claude Code",
    source: "claude",
    runtime: "Anthropic coding runtime",
    eventAtomMap: defaultEventAtomMap,
  },
  deepseek: {
    id: "deepseek",
    label: "DeepSeek",
    source: "deepseek",
    runtime: "DeepSeek Harness",
    eventAtomMap: defaultEventAtomMap,
  },
  opencode: {
    id: "opencode",
    label: "OpenCode",
    source: "opencode",
    runtime: "OpenCode coding runtime",
    eventAtomMap: defaultEventAtomMap,
  },
  zcode: {
    id: "zcode",
    label: "ZCode",
    source: "zcode",
    runtime: "ZCode coding runtime",
    eventAtomMap: defaultEventAtomMap,
  },
  trae: {
    id: "trae",
    label: "Trae",
    source: "trae",
    runtime: "Trae agent runtime",
    eventAtomMap: defaultEventAtomMap,
  },
  workbuddy: {
    id: "workbuddy",
    label: "WorkBuddy",
    source: "workbuddy",
    runtime: "Tencent CodeBuddy Code",
    eventAtomMap: defaultEventAtomMap,
  },
};

export const atomPlatformOptions = Object.values(platformDefinitions);

function resolvePlatform(platformId: string): PlatformDefinition {
  return platformDefinitions[platformId as PlatformId] || platformDefinitions.codex;
}

export function getAtomPlatformConfig(
  platformId: string = "codex",
): PlatformConfig {
  const platform = resolvePlatform(platformId);
  return {
    ...platform,
    layers,
    atoms,
    edges,
  };
}

export function getAtomIdForEvent(
  event: TraceEvent | null,
  platformId: string = "codex",
) {
  if (!event) return "";
  if (isUserQuestionEvent(event)) {
    return "harness-user-question";
  }
  const platform = resolvePlatform(platformId);
  const atomId = platform.eventAtomMap[event.eventName] || "trace-append";
  return `harness-${atomId}`;
}
